name: Deploy ExoTrack Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          set -e

          cd /var/www/exo-track-back

          echo "Updating code..."
          git pull origin main

          echo "Installing dependencies..."
          pnpm install --frozen-lockfile

          echo "Building application..."
          pnpm run build

          echo "Restarting service..."
          sudo systemctl restart exotrack-api

          echo "Deployment finished"